GET http://localhost:5222/games

###
GET http://localhost:5222/games/2

###
POST http://localhost:5222/games
Content-Type: application/json

{
    "Name": "Minecraft",
    "GenreId": 5,
    "Price": 19.99,
    "ReleaseDate": "2011-11-18"
}

###
POST http://localhost:5222/games
Content-Type: application/json

{
    "Name": "Street Fighter II",
    "GenreId": 1,
    "Price": 9.99,
    "ReleaseDate": "1991-02-01"
}

###
POST http://localhost:5222/games
Content-Type: application/json

{
    "Name": "Final Fantasy XIV",
    "GenreId": 4,
    "Price": 59.99,
    "ReleaseDate": "2010-09-30"
}
###
PUT http://localhost:5222/games/2
Content-Type: application/json

{
    "Name": "Street Fighter II Turbo",
    "GenreId": 2,
    "Price": 9.99,
    "ReleaseDate": "1991-02-01"
}

###
DELETE http://localhost:5222/games/4